<a href="https://colab.research.google.com/github/KuntaMallikRaj/meachine-learning/blob/main/DataPreprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

imported modules


In [8]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values



importing dataset

In [9]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [13]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy = 'mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [14]:
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [29]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [27]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)


[0 1 0 0 1 1 0 1 0 1]


In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2,random_state =1)

In [33]:
print(x_train)

[[0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [32]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [34]:
print(y_train)


[0 1 0 0 1 1 0 1]


In [35]:
print(y_test)


[0 1]


In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:,1:3] = sc.fit_transform(x_train[:,1:3])
x_train[:,1:3] = sc.transform(x_train[:,1:3])


In [39]:
print(x_train)

[[0.0 0.30900555126419443 -2.3745966692414835 -1.9106836025229594
  1.8920699974251831 -5.850195668168586 -5.528607982857564]
 [0.0 0.30900555126419443 -2.3745966692414835 3.4226497308103747
  -2.3745966692414835 -5.824425218771971 -5.528521714254413]
 [1.0 -3.957661115402472 1.8920699974251831 -1.9106836025229594
  -2.3745966692414835 -5.74008556620123 -5.528461489003156]
 [0.0 0.30900555126419443 -2.3745966692414835 -1.9106836025229594
  1.8920699974251831 -5.86659504505734 -5.528542060623081]
 [0.0 0.30900555126419443 -2.3745966692414835 -1.9106836025229594
  1.8920699974251831 -6.098529089626878 -5.528637281628446]
 [1.0 -3.957661115402472 1.8920699974251831 -1.9106836025229594
  -2.3745966692414835 -5.655745913630489 -5.528410216154113]
 [0.0 0.30900555126419443 -2.3745966692414835 3.4226497308103747
  -2.3745966692414835 -5.613576087345118 -5.528380917383233]
 [1.0 -3.957661115402472 1.8920699974251831 -1.9106836025229594
  -2.3745966692414835 -5.929849784485397 -5.52856403470124

In [40]:
print(x_test)

[[0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]
